// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB6iAfFq1AvVgutprFky2b1o615Rwhst4',
    appId: '1:852202901814:web:b45a9304a9a1b44dce2397',
    messagingSenderId: '852202901814',
    projectId: 'hood-happen-v2',
    authDomain: 'hood-happen-v2.firebaseapp.com',
    storageBucket: 'hood-happen-v2.firebasestorage.app',
    measurementId: 'G-3NP2JG9MZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfveFX3Q0GHWopX3_ACxqN03C4rw41CE',
    appId: '1:852202901814:android:0e9390e8d579f052ce2397',
    messagingSenderId: '852202901814',
    projectId: 'hood-happen-v2',
    storageBucket: 'hood-happen-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtcmwvXYLRH_T-3-mSiiFYBUXX70ugr8',
    appId: '1:852202901814:ios:f66167f2acbfdde0ce2397',
    messagingSenderId: '852202901814',
    projectId: 'hood-happen-v2',
    storageBucket: 'hood-happen-v2.firebasestorage.app',
    iosBundleId: 'com.example.hoodhappenCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtcmwvXYLRH_T-3-mSiiFYBUXX70ugr8',
    appId: '1:852202901814:ios:f66167f2acbfdde0ce2397',
    messagingSenderId: '852202901814',
    projectId: 'hood-happen-v2',
    storageBucket: 'hood-happen-v2.firebasestorage.app',
    iosBundleId: 'com.example.hoodhappenCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB6iAfFq1AvVgutprFky2b1o615Rwhst4',
    appId: '1:852202901814:web:3e60bef13fd4e697ce2397',
    messagingSenderId: '852202901814',
    projectId: 'hood-happen-v2',
    authDomain: 'hood-happen-v2.firebaseapp.com',
    storageBucket: 'hood-happen-v2.firebasestorage.app',
    measurementId: 'G-MJS38YZ2VX',
  );

}